-- Pre-built Table Box packages (Dinner for 8, House Full for 20).
--
-- Pricing stays data-driven:
--   * Each package is a real public.items row. Its rental_price is the
--     price the page shows AND the price Square charges.
--   * table_box_package_items maps the physical pieces inside a package, so
--     checkout can hold that inventory for the rental dates.
--   * Rows sharing a choice_group are alternatives: the customer picks one
--     per group (napkin colour, glass style, serving piece, centrepiece).
--     Rows with no choice_group are always included.
--   * table_box_package_addons lists the optional holiday add-ons, which
--     are also real items rows with their own rental_price.
--
-- Applied to production 2026-09-24. Package item ids 581/582 and every
-- component id below are the real rows in public.items.

create table if not exists public.table_box_packages (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  package_item_id bigint not null unique references public.items(id) on delete restrict,
  name text not null,
  guest_count integer not null check (guest_count > 0),
  blurb text,
  image_url text,
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.table_box_package_items (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.table_box_packages(id) on delete cascade,
  item_id bigint not null references public.items(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  label text,
  choice_group text,
  choice_label text,
  display_order integer not null default 0,
  unique (package_id, item_id)
);

create index if not exists table_box_package_items_package_id_idx
  on public.table_box_package_items (package_id);

create table if not exists public.table_box_package_addons (
  id bigint generated by default as identity primary key,
  item_id bigint not null unique references public.items(id) on delete restrict,
  label text,
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.table_box_packages enable row level security;
alter table public.table_box_package_items enable row level security;
alter table public.table_box_package_addons enable row level security;

drop policy if exists "Public can read active table box packages" on public.table_box_packages;
create policy "Public can read active table box packages"
on public.table_box_packages
for select
using (active = true);

drop policy if exists "Public can read table box package items" on public.table_box_package_items;
create policy "Public can read table box package items"
on public.table_box_package_items
for select
using (
  exists (
    select 1
    from public.table_box_packages p
    where p.id = table_box_package_items.package_id
      and p.active = true
  )
);

drop policy if exists "Public can read active table box package addons" on public.table_box_package_addons;
create policy "Public can read active table box package addons"
on public.table_box_package_addons
for select
using (active = true);

-- ------------------------------------------------------------
-- Seed (as applied)
-- ------------------------------------------------------------

-- Stock arriving for the 20-guest box: gold chargers and ribbed tumblers.
update public.items set quantity_owned = 30 where id in (574, 557);

-- The two package rows. category 'Table Box Package' is not a Decor or
-- Gifts tag, and table_box_category is null, so neither row shows up as a
-- loose catalogue item or gets its own item page.
-- Inserted without explicit ids; they came back as 581 and 582.
insert into public.items
  (name, category, description, photos, rental_price, quantity_owned, made_to_order,
   active, tracking_mode, inventory_type, tags)
values
  ('Dinner for 8 Table Box', 'Table Box Package',
   'For dinner parties, birthdays, showers and small holiday hosting.',
   '["/photos/black-gold-flatware-set-styled.png"]'::jsonb, 99, 999, false,
   true, 'quantity', 'returnable', '{}'),
  ('House Full for 20 Table Box', 'Table Box Package',
   'For larger gatherings, holiday hosting and the whole house coming over.',
   '["/photos/classic-white-dinner-plate-with-charger.png"]'::jsonb, 229, 999, false,
   true, 'quantity', 'returnable', '{}');

insert into public.table_box_packages
  (slug, package_item_id, name, guest_count, blurb, image_url, display_order)
values
  ('dinner-for-8', 581, 'Dinner for 8', 8,
   'For dinner parties, birthdays, showers and small holiday hosting.',
   '/photos/black-gold-flatware-set-styled.png', 10),
  ('house-full-for-20', 582, 'House Full for 20', 20,
   'For larger gatherings, holiday hosting and the whole house coming over.',
   '/photos/classic-white-dinner-plate-with-charger.png', 20)
on conflict (slug) do update
set package_item_id = excluded.package_item_id, name = excluded.name,
    guest_count = excluded.guest_count, blurb = excluded.blurb,
    image_url = excluded.image_url, display_order = excluded.display_order, active = true;

-- Dinner for 8
insert into public.table_box_package_items
  (package_id, item_id, quantity, label, choice_group, choice_label, display_order)
select p.id, x.item_id, x.quantity, x.label, x.choice_group, x.choice_label, x.display_order
from public.table_box_packages p
cross join (
  values
    (578, 8, 'white dinner plates', null, null, 10),
    (574, 8, 'gold chargers', null, null, 20),
    (580, 8, 'black + gold flatware settings', null, null, 30),
    (557, 8, 'ribbed water glasses', null, null, 40),
    (558, 8, 'ribbed glass goblets', 'glasses', 'Wine glasses', 50),
    (449, 8, 'unbreakable crystal clear wine glasses', 'glasses', 'Wine glasses', 51),
    (567, 8, 'ivory cloth napkins', 'napkins', 'Napkin colour', 60),
    (568, 8, 'emerald cloth napkins', 'napkins', 'Napkin colour', 61),
    (569, 8, 'coral cloth napkins', 'napkins', 'Napkin colour', 62),
    (570, 8, 'black cloth napkins', 'napkins', 'Napkin colour', 63),
    (577, 2, 'ribbed glass candle holders', null, null, 70),
    (573, 1, 'ribbed glass serving dish', 'serving', 'Serving piece', 80),
    (540, 1, 'glass serving tray', 'serving', 'Serving piece', 81)
) as x(item_id, quantity, label, choice_group, choice_label, display_order)
where p.slug = 'dinner-for-8'
on conflict (package_id, item_id) do update
set quantity = excluded.quantity, label = excluded.label, choice_group = excluded.choice_group,
    choice_label = excluded.choice_label, display_order = excluded.display_order;

-- House Full for 20. Both serving pieces are included (1 of each is owned).
-- The goblet option stays mapped but the page hides it until 20+ are owned.
insert into public.table_box_package_items
  (package_id, item_id, quantity, label, choice_group, choice_label, display_order)
select p.id, x.item_id, x.quantity, x.label, x.choice_group, x.choice_label, x.display_order
from public.table_box_packages p
cross join (
  values
    (578, 20, 'white dinner plates', null, null, 10),
    (574, 20, 'gold chargers', null, null, 20),
    (580, 20, 'black + gold flatware settings', null, null, 30),
    (557, 20, 'ribbed water glasses', null, null, 40),
    (558, 20, 'ribbed glass goblets', 'glasses', 'Wine glasses', 50),
    (449, 20, 'unbreakable crystal clear wine glasses', 'glasses', 'Wine glasses', 51),
    (567, 20, 'ivory cloth napkins', 'napkins', 'Napkin colour', 60),
    (568, 20, 'emerald cloth napkins', 'napkins', 'Napkin colour', 61),
    (569, 20, 'coral cloth napkins', 'napkins', 'Napkin colour', 62),
    (570, 20, 'black cloth napkins', 'napkins', 'Napkin colour', 63),
    (577, 6, 'ribbed glass candle holders', null, null, 70),
    (573, 1, 'ribbed glass serving dish', null, null, 80),
    (540, 1, 'glass serving tray', null, null, 81),
    (491, 1, 'floral hoop centrepiece', 'centrepiece', 'Centrepiece', 90),
    (445, 1, 'peach and gold mini centrepiece set', 'centrepiece', 'Centrepiece', 91)
) as x(item_id, quantity, label, choice_group, choice_label, display_order)
where p.slug = 'house-full-for-20'
on conflict (package_id, item_id) do update
set quantity = excluded.quantity, label = excluded.label, choice_group = excluded.choice_group,
    choice_label = excluded.choice_label, display_order = excluded.display_order;

-- Holiday add-ons
insert into public.table_box_package_addons (item_id, label, display_order)
values
  (497, 'Garland', 10),
  (498, 'String lights', 20),
  (576, 'Seasonal floral centrepiece', 30)
on conflict (item_id) do update
set label = excluded.label, display_order = excluded.display_order, active = true;
